<a href="https://colab.research.google.com/github/aymen-cyber/colab_test/blob/main/text_embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding

In [2]:
Sent = ['Hello, how are you',
        'how are you',
        'how are you doing',
        'I am doing great',
        'I am doing good',
        'I am good']

In [3]:
sent_labels = array([1,1,1,0,0,0])

In [4]:
my_vocab_size = 30
encoded_sent = [one_hot(i, my_vocab_size) for i in Sent]
print(encoded_sent)

[[4, 23, 25, 18], [23, 25, 18], [23, 25, 18, 24], [5, 29, 24, 16], [5, 29, 24, 12], [5, 29, 12]]


In [22]:
length = 5
padded_sent = pad_sequences(encoded_sent, maxlen=length, padding='post')
print(padded_sent)

[[ 4 23 25 18  0]
 [23 25 18  0  0]
 [23 25 18 24  0]
 [ 5 29 24 16  0]
 [ 5 29 24 12  0]
 [ 5 29 12  0  0]]


In [8]:
mymodel = Sequential()
mymodel.add(Embedding(my_vocab_size, 8, input_length=length))
mymodel.add(Flatten())
mymodel.add(Dense(1, activation='sigmoid'))

In [9]:
mymodel.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [12]:
mymodel.fit(padded_sent, sent_labels, epochs=30)

# evaluate the model
modelloss, modelaccuracy = mymodel.evaluate(padded_sent, sent_labels, verbose=0)
print('Accuracy: %f' % (modelaccuracy*100))

Epoch 1/30
1/1 [==============================] - 1s 933ms/step - loss: 0.6830 - accuracy: 0.5000
Epoch 2/30
1/1 [==============================] - 0s 13ms/step - loss: 0.6810 - accuracy: 0.5000
Epoch 3/30
1/1 [==============================] - 0s 6ms/step - loss: 0.6791 - accuracy: 0.6667
Epoch 4/30
1/1 [==============================] - 0s 8ms/step - loss: 0.6771 - accuracy: 0.6667
Epoch 5/30
1/1 [==============================] - 0s 5ms/step - loss: 0.6751 - accuracy: 0.8333
Epoch 6/30
1/1 [==============================] - 0s 7ms/step - loss: 0.6732 - accuracy: 0.8333
Epoch 7/30
1/1 [==============================] - 0s 6ms/step - loss: 0.6712 - accuracy: 0.8333
Epoch 8/30
1/1 [==============================] - 0s 7ms/step - loss: 0.6693 - accuracy: 0.8333
Epoch 9/30
1/1 [==============================] - 0s 12ms/step - loss: 0.6673 - accuracy: 0.8333
Epoch 10/30
1/1 [==============================] - 0s 6ms/step - loss: 0.6653 - accuracy: 0.8333
Epoch 11/30
1/1 [==================

In [13]:
mysent_to_predict = ['how are you Suman',
        'I am good']

In [14]:
vocab_size = 30
encoded = [one_hot(d, vocab_size) for d in mysent_to_predict]
print(encoded)

[[23, 25, 18, 14], [5, 29, 12]]


In [15]:
max_length = 5
mypadded = pad_sequences(encoded, maxlen=max_length, padding='pre')
print(mypadded)

[[ 0 23 25 18 14]
 [ 0  0  5 29 12]]


In [21]:
predictions = (mymodel.predict(mypadded) > 0.5).astype("int32")
mymodel.predict(mypadded)

array([[0.5232605 ],
       [0.49411085]], dtype=float32)

In [20]:
predictions

array([[1],
       [0]], dtype=int32)